version: '3.9'

services:

  database:
    image: mysql
    restart: always
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: jskdoenswpsfi
      MYSQL_DATABASE: users

  backend:
    build: ./backend
    restart: always
    ports:
      - 5000:80
    depends_on:
      - database
    entrypoint: ["./wait-for-it.sh", "database:3306", "--", "gunicorn", "app:app", "-b", "0.0.0.0:80", "-w", "1"]
    environment:
      DB_URL: database
      DB_USER: root
      DB_PASS: jskdoenswpsfi

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_BACKEND=http://localhost:5000
    restart: always
    ports:
      - 8080:80
    depends_on:
      - backend
